### ISSUE TITLE
Notice: Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by gintechsystems** [BoldGrid/boldgrid-backup#387]
Receiving warnings when I login to WordPress and go to my dashboard. I am using the latest WordPress version (5.5.1).

```
Notice: Trying to access array offset on value of type bool in /home/coginc5/test/wp-content/plugins/boldgrid-backup/vendor/boldgrid/library/src/Library/Dashboard/SortWidgets.php on line 75

Notice: Trying to access array offset on value of type bool in /home/coginc5/test/wp-content/plugins/boldgrid-backup/vendor/boldgrid/library/src/Library/Dashboard/SortWidgets.php on line 75

Notice: Trying to access array offset on value of type bool in /home/coginc5/test/wp-content/plugins/boldgrid-backup/vendor/boldgrid/library/src/Library/Dashboard/SortWidgets.php on line 75

Notice: Trying to access array offset on value of type bool in /home/coginc5/test/wp-content/plugins/boldgrid-backup/vendor/boldgrid/library/src/Library/Dashboard/SortWidgets.php on line 75

Warning: Cannot modify header information - headers already sent by (output started at /home/coginc5/test/wp-content/plugins/boldgrid-backup/vendor/boldgrid/library/src/Library/Dashboard/SortWidgets.php:75) in /home/coginc5/test/wp-admin/admin-header.php on line 9
```

**Comment by bwmarkle** [comment]
Hi @gintechsystems thanks for taking the time to create a GitHub issue. I found [the line where the issue is occurring](https://github.com/BoldGrid/library/blob/master/src/Library/Dashboard/SortWidgets.php#L75), and it should be a quick fix. I'll keep you updated.

Also, while I think it's a quick fix, I'd like to be able to replicate the issue during testing. For this though, I'm not sure if you'd be able to give us steps to replicate the problem - we'd require a list of the plugins you're running / etc. Is there anything abnormal about your dashboard that you think maybe be a part of the issue?

**Comment by gintechsystems** [comment]
I can try my best. The steps were simple, I login to WordPress backend using my credentials. Once I login and see the home dashboard, the warnings display at the top. See attached photo. I will get you the list of plugins soon.

![image](https://user-images.githubusercontent.com/10021307/92281082-e02ae980-eec8-11ea-9d4f-a7e0accbf013.png)

**Comment by gintechsystems** [comment]
Here is a screenshot of our plugins. We do not have many. Kind of interesting, I don't even see the BoldGrid plugin. It seemed to have disappeared? We are using InMotion Hosting and they provided it with our WP installation.

![image](https://user-images.githubusercontent.com/10021307/92281225-208a6780-eec9-11ea-8e6d-0e3f8efb9943.png)

**Comment by bwmarkle** [comment]
Hi @gintechsystems, just wanted to let you know we released a patch yesterday to avoid these warnings. Thanks for bringing it to our attention!

**Comment by gintechsystems** [comment]
Thank you, this seems to be working fine now!
